WARNING: you may need to modify /home/isaacwp/.config/docker/daemon.json to
pull images; see
https://github.com/docker/for-linux/issues/1172#issuecomment-771929216 
Running training with line graph partitions
Simulated graph file doesn't exist, generating file...
Generating graph data
Graphs generated, time: 0.0586550235748291
Args in experiment:
Namespace(activation='gelu', attn='prob', batch_size=32, c_out=100, checkpoints='./checkpoints/', cols=None, d_ff=2048, d_layers=1, d_model=512, data='sim_graph', data_path='lg_n10_t10.csv', dec_in=400, des='lg_n10_t10_test', detail_freq='d', device_ids=[0, 1, 2, 3], devices='0,1,2,3', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=400, factor=5, features='M', freq='d', gpu=0, inverse=False, itr=2, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', m_true_len=100, mix=True, model='informer', n_heads=8, num_workers=0, output_attention=False, padding=0, patience=3, pred_len=24, root_path='./data/', s_layers=[3, 2, 1], seq_len=96, target='none', train_epochs=6, use_amp=False, use_gpu=True, use_multi_gpu=True)
Use GPU: cuda:0
>>>>>>>start training : informer_sim_graph_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_lg_n10_t10_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
features M
Traceback (most recent call last):
  File "./main_informer.py", line 107, in <module>
    exp.train(setting)
  File "/home/isaacwp/Informer2020/exp/exp_informer.py", line 128, in train
    train_data, train_loader = self._get_data(flag = 'train')
  File "/home/isaacwp/Informer2020/exp/exp_informer.py", line 97, in _get_data
    print(flag, len(data_set))
ValueError: __len__() should return >= 0
